spring.config.import=file:env.properties
spring.application.name=ow_5v5_build
# SERVER CONFIG
server.port=${PORTA}
#DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
#JWT
jwt.secret=${JWT_SECRET}
#CLOUDINARY
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
#MAILGUN
mg.apikey=${MG_API_KEY}
mg.domain=${MG_DOMAIN}
mg.from=${MG_FROM}
mg.base-url=${BASE_URL}
#SYS_ADMIN
admin.username=${ADMIN_USERNAME}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PSW}